### ISSUE TITLE
Ubuntu 22.04

### ISSUE THREAD

**Issue by gtach2o** [SAP/SapMachine-infrastructure#26]
Hi!

Do you plan to use Ubuntu 22.04 LTS as a base image?

Thanks!

**Comment by RealCLanger** [comment]
Hi,
we'll be looking into that. Let's keep this issue open for the time being...
Cheers
Christoph

**Comment by gtach2o** [comment]
@RealCLanger I think it can be closed now.

**Comment by RealCLanger** [comment]
> @RealCLanger I think it can be closed now.

Correct, ubuntu base image release has been updated in April 2023 updates.
