### ISSUE TITLE
sapmachine:20 apt-get update fails

### ISSUE THREAD

**Issue by gtach2o** [SAP/SapMachine-infrastructure#37]
the error message
```
W: http://security.ubuntu.com/ubuntu/dists/jammy-security/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/sapmachine.gpg.asc are ignored as the file is not readable by user '_apt' executing apt-key.
W: http://security.ubuntu.com/ubuntu/dists/jammy-security/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/ubuntu-keyring-2012-cdimage.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
W: http://security.ubuntu.com/ubuntu/dists/jammy-security/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/ubuntu-keyring-2018-archive.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
W: GPG error: http://security.ubuntu.com/ubuntu jammy-security InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
E: The repository 'http://security.ubuntu.com/ubuntu jammy-security InRelease' is not signed.
....
```

**Comment by gtach2o** [comment]
@RealCLanger Could you please take a look?

**Comment by RealCLanger** [comment]
Hi @gtach2o,

I can not really follow your reported problem. I just ran the .deb instructions from https://github.com/SAP/SapMachine/wiki/Installation in an Ubuntu 22 container and had no issues.

I guess you ran apt-get update. Maybe as a non-root user?

This error text indicates some permission problems:
The key(s) in the keyring /etc/apt/trusted.gpg.d/sapmachine.gpg.asc are ignored as the file is not readable by user '_apt' executing apt-key. The same obviously applies to the ubuntu keys.

Maybe run "sudo apt-get update" ?

Cheers
Christoph

**Comment by gtach2o** [comment]
When I run it locally I have no issue as well. 
This error happens in build environment where some remote resources can be not available. 
This issue did not happen for 20.04

**Comment by gtach2o** [comment]
Got it fixed.
Thank you.

**Comment by gtach2o** [comment]
> > Got it fixed. Thank you.
> 
> Great, I'm glad you could resolve it. 😄

yeah, but now I'm getting issue with gradle running on that image

when I'm running a test with gradle I'm getting this error

```
ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/sapmachine-20

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```
I think image has nothing to do with it, but again it didn't happend with the image based on 20.04 😞

**Comment by gtach2o** [comment]
Gradle error has gone after Docker been updated to the latest version.
