### ISSUE TITLE
Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by gtach2o** [SAP/SapMachine-infrastructure#43]
Hi!

Any plan to update the base image?

**Comment by RealCLanger** [comment]
Hi,
yes, we'll add Ubuntu 24.04 based images. They will appear soon.

**Comment by gtach2o** [comment]
Also, as an idea, could be possible to use LTS Ubuntu for Java LTS images and use latest Ubuntu for latest Java?

**Comment by RealCLanger** [comment]
We've updated our Ubuntu docker images with https://github.com/docker-library/official-images/pull/16764 and now provide base images for Ubuntu 24.04, 22.04 and 20.04.
